name: 'Setup Bazel'
description: 'Setup and configure bazel for CI use'
author: 'Angular'

inputs:
  bazelrc:
    default: .bazelrc.user
    description: |
      The `bazelrc` file location to add the `repository_cache` flag to. Defaults
      to .bazelrc.user

runs:
  using: composite
  steps:
    - name: Configure action caching for bazel version downloaded by bazelisk
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # tag=v3.3.1
      with:
        path: |
          ~/.cache/bazelisk
          \%LocalAppData\%/bazelisk
        key: bazel-version-${{ hashFiles('**/.bazelversion') }}

    - name: Setup CI bazelrc config
      run: node $GITHUB_ACTION_PATH/setup-ci-bazelrc.mjs
      env:
        BAZELRC_PATH: ${{ inputs.bazelrc }}
      shell: bash

    - name: Configure action caching for bazel repository cache
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # tag=v3.3.1
      with:
        # Note: Bazel repository cache is located in system locations and cannot use
        # a shared cache between different runner operating systems.
        path: '~/.cache/bazel_repo_cache'
        key: bazel-cache-${{ runner.os }}-${{ hashFiles('**/WORKSPACE') }}
        restore-keys: |
          bazel-cache-${{ runner.os }}-
