name: 'Setup Bazel'
description: 'Setup and configure bazel for CI use'
author: 'Angular'

nputs:
  bazelrc:
    default: .bazelrc.user
    description: |
      The `bazelrc` file location to add the `repository_cache` flag to. Defaults
      to .bazelrc.user

runs:
  using: composite
  steps:
    - name: Add repository cache directory to bazelrc config
      run: ${{ github.action_path }}/add-repository-cache.sh
      env:
        BAZELRC_PATH: ${{ inputs.bazelrc }}
      shell: bash

    - name: Configure action caching for bazel repository cache
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # tag=v3.3.1
      with:
        enableCrossOsArchive: true
        path: |
          ~/bazel_repository_cache
        key: bazel-cache-${{ hashFiles('**/WORKSPACE') }}
        restore-keys: |
          bazel-cache-

    - name: Configure action caching for downloaded bazel artifacts
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # tag=v3.3.1
      with:
        path: |
          ~/.cache/bazelisk
        key: bazel-version-${{ runner.os }}-${{ hashFiles('**/.bazelversion') }}
        restore-keys: |
          bazel-version-${{ runner.os }}-
