name: 'Setup Bazel'
description: 'Setup and configure bazel for CI use'
author: 'Angular'

inputs:
  bazelrc:
    default: .bazelrc.user
    description: |
      The `bazelrc` file location to add the `repository_cache` flag to. Defaults
      to .bazelrc.user

runs:
  using: composite
  steps:
    - name: Configure action caching for bazel version downloaded by bazelisk
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: |
          ~/.cache/bazelisk
          ~/AppData/Local/bazelisk
        key: bazel-version-${{ runner.os }}-${{ hashFiles('**/.bazelversion') }}

    - name: Setup CI bazelrc config
      run: node $GITHUB_ACTION_PATH/setup-ci-bazelrc.mjs
      env:
        BAZELRC_PATH: ${{ inputs.bazelrc }}
      shell: bash

    - name: Configure action caching for bazel repository cache
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        # Note: Bazel repository cache is located in system locations and cannot use
        # a shared cache between different runner operating systems.
        path: '~/.cache/bazel_repo_cache'
        key: bazel-cache-${{ runner.os }}-${{ hashFiles('**/WORKSPACE') }}-${{ hashFiles('**/MODULE.bazel.lock') }}
        restore-keys: |
          bazel-cache-${{ runner.os }}-
