"""Rules/toolchains for devinfra with Bazel."""

module(
    name = "devinfra",
)

register_toolchains(
    "//bazel/git-toolchain:git_linux_toolchain",
    "//bazel/git-toolchain:git_macos_x86_toolchain",
    "//bazel/git-toolchain:git_macos_arm64_toolchain",
)

bazel_dep(name = "yq.bzl", version = "0.3.6")
bazel_dep(name = "tar.bzl", version = "0.10.8")
bazel_dep(name = "bazel_lib", version = "3.7.1")
bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "aspect_rules_js", version = "3.4.0")
bazel_dep(name = "rules_pkg", version = "1.3.0")
bazel_dep(name = "aspect_rules_jasmine", version = "2.0.4")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "aspect_rules_esbuild", version = "0.27.0")
bazel_dep(name = "aspect_rules_ts", version = "3.10.0")
bazel_dep(name = "rules_nodejs", version = "6.7.5")
bazel_dep(name = "rules_browsers")
local_path_override(
    module_name = "rules_browsers",
    path = "bazel/rules/rules_browsers",
)

bazel_dep(name = "rules_sass", dev_dependency = True)
local_path_override(
    module_name = "rules_sass",
    path = "bazel/rules/rules_sass",
)

bazel_dep(name = "rules_angular", dev_dependency = True)
local_path_override(
    module_name = "rules_angular",
    path = "bazel/rules/rules_angular",
)

yq = use_extension("@yq.bzl//yq:extensions.bzl", "yq")
use_repo(yq, "yq_toolchains")

rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext")
rules_ts_ext.deps(
    # Obtained by: curl --silent https://registry.npmjs.org/typescript/5.9.3 | jq -r '.dist.integrity'
    ts_integrity = "sha512-y2TvuxSZPDyQakkFRPZHKFm+KKVqIisdg9/CZwm9ftvKXLP8NRWj38/ODjNbr43SsoXqNuAisEf1GdCxqWcdBw==",
    ts_version = "6.0.3",
)
use_repo(rules_ts_ext, "npm_typescript")

node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
node.toolchain(
    node_repositories = {
        "24.19.0-darwin_arm64": ("node-v24.19.0-darwin-arm64.tar.gz", "node-v24.19.0-darwin-arm64", "8294b7aa9b03997481c06babf1e8b270c859358f27da57a11509afe537ac381d"),
        "24.19.0-darwin_amd64": ("node-v24.19.0-darwin-x64.tar.gz", "node-v24.19.0-darwin-x64", "d1b5e999db158c62fe8f7267a4476b035d8bd93b1a605bac24a3f0dd166e3316"),
        "24.19.0-linux_arm64": ("node-v24.19.0-linux-arm64.tar.xz", "node-v24.19.0-linux-arm64", "01443c1e1a29e531ccad5a46fefa6df490d2189c49f7955904aecdbb0fe86fdc"),
        "24.19.0-linux_ppc64le": ("node-v24.19.0-linux-ppc64le.tar.xz", "node-v24.19.0-linux-ppc64le", "c510c6ce12f07010f771e6edb22a3fe23f4f2e6f40b1ffd4941aed0646a0d8b3"),
        "24.19.0-linux_s390x": ("node-v24.19.0-linux-s390x.tar.xz", "node-v24.19.0-linux-s390x", "a4792e65962ffa0af42627aacf1122a60c3c88dbf4e4184f06820d66f9da8ba4"),
        "24.19.0-linux_amd64": ("node-v24.19.0-linux-x64.tar.xz", "node-v24.19.0-linux-x64", "14b342e71204f811bde6153be8e04b62aef63c236fef92b55f9c83154b409647"),
        "24.19.0-windows_amd64": ("node-v24.19.0-win-x64.zip", "node-v24.19.0-win-x64", "57f71ab3652e797d84acddc79c81cc9ff1c6ddb2a1974cdb83f00fee9bff4c73"),
    },
    node_version = "24.19.0",
)
use_repo(node, "nodejs_toolchains")

rules_angular = use_extension("@rules_angular//setup:extensions.bzl", "rules_angular", dev_dependency = True)
rules_angular.setup(
    name = "dev_infra_rules_angular_configurable_deps",
    angular_compiler_cli = "//:node_modules/@angular/compiler-cli",
    typescript = "//:node_modules/typescript",
)
use_repo(rules_angular, rules_angular_configurable_deps = "dev_infra_rules_angular_configurable_deps")

pnpm = use_extension("@aspect_rules_js//npm:extensions.bzl", "pnpm")
pnpm.pnpm(
    name = "pnpm",
    pnpm_version = "11.24.0",
    pnpm_version_integrity = "sha512-vSfjRel23LC+C3oSKCF7BJqBfiGx81XJDb59xGZxiVqLwebQbCRVRQXqk+oLRfSJon7Bv7yN5qlln8oPFvoAAA==",
)
use_repo(pnpm, "pnpm")

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
npm.npm_translate_lock(
    name = "devinfra_npm",
    data = [
        "@devinfra//.github/local-actions:package.json",
        "@devinfra//.github/local-actions/branch-manager:package.json",
        "@devinfra//.github/local-actions/labels-sync:package.json",
        "@devinfra//.github/local-actions/lock-closed:package.json",
        "@devinfra//:package.json",
        "@devinfra//:pnpm-workspace.yaml",
        "@devinfra//apps/code-of-conduct:package.json",
        "@devinfra//apps/functions:package.json",
        "@devinfra//bazel:package.json",
        "@devinfra//bazel/spec-bundling/test:package.json",
        "@devinfra//github-actions:package.json",
        "@devinfra//github-actions/bazel/configure-remote:package.json",
        "@devinfra//github-actions/branch-manager:package.json",
        "@devinfra//github-actions/browserstack:package.json",
        "@devinfra//github-actions/google-internal-tests:package.json",
        "@devinfra//github-actions/labeling/issue:package.json",
        "@devinfra//github-actions/labeling/pull-request:package.json",
        "@devinfra//github-actions/org-file-sync:package.json",
        "@devinfra//github-actions/post-approval-changes:package.json",
        "@devinfra//github-actions/previews/pack-and-upload-artifact:package.json",
        "@devinfra//github-actions/previews/upload-artifacts-to-firebase:package.json",
        "@devinfra//github-actions/saucelabs:package.json",
        "@devinfra//github-actions/unified-status-check:package.json",
        "@devinfra//ng-dev:package.json",
    ],
    pnpm_lock = "@devinfra//:pnpm-lock.yaml",
)
use_repo(npm, "devinfra_npm")
