"""Rules/toolchains for devinfra with Bazel."""

module(
    name = "devinfra",
)

register_toolchains(
    "//bazel/git-toolchain:git_linux_toolchain",
    "//bazel/git-toolchain:git_macos_x86_toolchain",
    "//bazel/git-toolchain:git_macos_arm64_toolchain",
)

bazel_dep(name = "yq.bzl", version = "0.4.0")
bazel_dep(name = "tar.bzl", version = "0.10.8")
bazel_dep(name = "bazel_lib", version = "3.7.2")
bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "aspect_rules_js", version = "3.4.1")
bazel_dep(name = "rules_pkg", version = "1.3.0")
bazel_dep(name = "aspect_rules_jasmine", version = "2.0.4")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "aspect_rules_esbuild", version = "0.27.0")
bazel_dep(name = "aspect_rules_ts", version = "3.10.1")
bazel_dep(name = "rules_nodejs", version = "6.7.5")
bazel_dep(name = "rules_browsers")
local_path_override(
    module_name = "rules_browsers",
    path = "bazel/rules/rules_browsers",
)

bazel_dep(name = "rules_sass", dev_dependency = True)
local_path_override(
    module_name = "rules_sass",
    path = "bazel/rules/rules_sass",
)

bazel_dep(name = "rules_angular", dev_dependency = True)
local_path_override(
    module_name = "rules_angular",
    path = "bazel/rules/rules_angular",
)

yq = use_extension("@yq.bzl//yq:extensions.bzl", "yq")
use_repo(yq, "yq_toolchains")

rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext")
rules_ts_ext.deps(
    # Obtained by: curl --silent https://registry.npmjs.org/typescript/5.9.3 | jq -r '.dist.integrity'
    ts_integrity = "sha512-y2TvuxSZPDyQakkFRPZHKFm+KKVqIisdg9/CZwm9ftvKXLP8NRWj38/ODjNbr43SsoXqNuAisEf1GdCxqWcdBw==",
    ts_version = "6.0.3",
)
use_repo(rules_ts_ext, "npm_typescript")

node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
node.toolchain(
    node_repositories = {
        "24.20.0-darwin_arm64": ("node-v24.20.0-darwin-arm64.tar.gz", "node-v24.20.0-darwin-arm64", "40e5607e5ecb3db9192723776da2d75d966260fc74a7a9e731c1bd67dda96bc8"),
        "24.20.0-darwin_amd64": ("node-v24.20.0-darwin-x64.tar.gz", "node-v24.20.0-darwin-x64", "9e5b2644cf107befb6aefca676b96d3296bc10138096f022ed378d6233ed81f4"),
        "24.20.0-linux_arm64": ("node-v24.20.0-linux-arm64.tar.xz", "node-v24.20.0-linux-arm64", "5f4ddab610c1ab2016b3c227cebdbf6d9495161487e4739c7b90090595f465f7"),
        "24.20.0-linux_ppc64le": ("node-v24.20.0-linux-ppc64le.tar.xz", "node-v24.20.0-linux-ppc64le", "341307dcee20d88332307008f2a480450c54f42d5149e7c4c8a18d937e37b5c1"),
        "24.20.0-linux_s390x": ("node-v24.20.0-linux-s390x.tar.xz", "node-v24.20.0-linux-s390x", "ca381121cb5a8d38c2954b6699cea09a83fba1b03141a71a8348f08df02de245"),
        "24.20.0-linux_amd64": ("node-v24.20.0-linux-x64.tar.xz", "node-v24.20.0-linux-x64", "2f2c0da162318f0de47665410c7c8c2ed3d36c8f3105de4bbc61176c70a7cbf2"),
        "24.20.0-windows_amd64": ("node-v24.20.0-win-x64.zip", "node-v24.20.0-win-x64", "6cac9ffbca8f6a47091e4b5c772e0606049c3871cb67d900c0cedde630e545ba"),
    },
    node_version = "24.20.0",
)
use_repo(node, "nodejs_toolchains")

rules_angular = use_extension("@rules_angular//setup:extensions.bzl", "rules_angular", dev_dependency = True)
rules_angular.setup(
    name = "dev_infra_rules_angular_configurable_deps",
    angular_compiler_cli = "//:node_modules/@angular/compiler-cli",
    typescript = "//:node_modules/typescript",
)
use_repo(rules_angular, rules_angular_configurable_deps = "dev_infra_rules_angular_configurable_deps")

pnpm = use_extension("@aspect_rules_js//npm:extensions.bzl", "pnpm")
pnpm.pnpm(
    name = "pnpm",
    pnpm_version = "11.24.0",
    pnpm_version_integrity = "sha512-vSfjRel23LC+C3oSKCF7BJqBfiGx81XJDb59xGZxiVqLwebQbCRVRQXqk+oLRfSJon7Bv7yN5qlln8oPFvoAAA==",
)
use_repo(pnpm, "pnpm")

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
npm.npm_translate_lock(
    name = "devinfra_npm",
    data = [
        "@devinfra//.github/local-actions:package.json",
        "@devinfra//.github/local-actions/branch-manager:package.json",
        "@devinfra//.github/local-actions/labels-sync:package.json",
        "@devinfra//.github/local-actions/lock-closed:package.json",
        "@devinfra//:package.json",
        "@devinfra//:pnpm-workspace.yaml",
        "@devinfra//apps/code-of-conduct:package.json",
        "@devinfra//apps/functions:package.json",
        "@devinfra//bazel:package.json",
        "@devinfra//bazel/spec-bundling/test:package.json",
        "@devinfra//github-actions:package.json",
        "@devinfra//github-actions/bazel/configure-remote:package.json",
        "@devinfra//github-actions/branch-manager:package.json",
        "@devinfra//github-actions/browserstack:package.json",
        "@devinfra//github-actions/google-internal-tests:package.json",
        "@devinfra//github-actions/labeling/issue:package.json",
        "@devinfra//github-actions/labeling/pull-request:package.json",
        "@devinfra//github-actions/org-file-sync:package.json",
        "@devinfra//github-actions/post-approval-changes:package.json",
        "@devinfra//github-actions/previews/pack-and-upload-artifact:package.json",
        "@devinfra//github-actions/previews/upload-artifacts-to-firebase:package.json",
        "@devinfra//github-actions/saucelabs:package.json",
        "@devinfra//github-actions/unified-status-check:package.json",
        "@devinfra//ng-dev:package.json",
    ],
    pnpm_lock = "@devinfra//:pnpm-lock.yaml",
)
use_repo(npm, "devinfra_npm")
