packages:
  - .
minimumReleaseAge: 1440
# List of packages to exclude from the minimum release age check.
minimumReleaseAgeExclude:
  - '@angular-devkit/*'
  - '@angular/*'
  - '@schematics/*'
packageExtensions:
  grpc-gcp:
    peerDependencies:
      protobufjs: '*'
engineStrict: true
hoist: false
autoInstallPeers: false
allowBuilds: {'@parcel/watcher': false, esbuild: false, lmdb: false, msgpackr-extract: false}
