name: 'Post Approval Changes'
description: 'Ensure that unexpected post approval changes do not occur'
author: 'Angular'
inputs:
  angular-robot-key:
    description: 'The private key for the Angular Robot Github app.'
    required: true
runs:
  using: 'node12'
  main: 'main.js'
  post: 'post.js'
