load("@devinfra_npm//:defs.bzl", "npm_link_all_packages")
load("//tools:defaults.bzl", "esbuild_checked_in", "ts_project")

npm_link_all_packages()

ts_project(
    name = "browserstack",
    srcs = glob(["*.ts"]),
    tsconfig = "//github-actions:tsconfig",
    deps = [
        ":node_modules/@actions/core",
        ":node_modules/@types/node",
    ],
)

esbuild_checked_in(
    name = "set-browserstack-env",
    srcs = [":browserstack"],
    entry_point = "index.ts",
    format = "iife",
    platform = "node",
)
