"""Rules/toolchains to use browsers with Bazel."""

module(
    name = "rules_browsers",
    version = "0.4.0",
)

# Load default browser versions used by targets in `//browsers` for direct consumption. Test rules
# provided from the module use these repositories transitively. The root module depending on
# `rules_browsers` can override the version used in its `MODULE.bazel` file.
browsers = use_extension("//browsers:extensions.bzl", "browsers")
browsers.chrome()
browsers.chromedriver()
browsers.firefox()
use_repo(
    browsers,
    "rules_browsers_chrome_linux",
    "rules_browsers_chrome_mac",
    "rules_browsers_chrome_mac_arm",
    "rules_browsers_chrome_win64",
    "rules_browsers_chromedriver_linux",
    "rules_browsers_chromedriver_mac",
    "rules_browsers_chromedriver_mac_arm",
    "rules_browsers_chromedriver_win64",
    "rules_browsers_firefox_linux",
    "rules_browsers_firefox_mac",
    "rules_browsers_firefox_mac_arm",
    "rules_browsers_firefox_win64",
)

# Miscellaneous dependencies.
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "bazel_skylib", version = "1.9.2")

# Dev dependencies
bazel_dep(name = "devinfra", dev_dependency = True)
local_path_override(
    module_name = "devinfra",
    path = "../../../",
)

# Manually specify a recent Node.js version.
bazel_dep(name = "rules_nodejs", version = "6.7.5")

node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
node.toolchain(
    node_repositories = {
        "24.19.0-darwin_arm64": ("node-v24.19.0-darwin-arm64.tar.gz", "node-v24.19.0-darwin-arm64", "8294b7aa9b03997481c06babf1e8b270c859358f27da57a11509afe537ac381d"),
        "24.19.0-darwin_amd64": ("node-v24.19.0-darwin-x64.tar.gz", "node-v24.19.0-darwin-x64", "d1b5e999db158c62fe8f7267a4476b035d8bd93b1a605bac24a3f0dd166e3316"),
        "24.19.0-linux_arm64": ("node-v24.19.0-linux-arm64.tar.xz", "node-v24.19.0-linux-arm64", "01443c1e1a29e531ccad5a46fefa6df490d2189c49f7955904aecdbb0fe86fdc"),
        "24.19.0-linux_ppc64le": ("node-v24.19.0-linux-ppc64le.tar.xz", "node-v24.19.0-linux-ppc64le", "c510c6ce12f07010f771e6edb22a3fe23f4f2e6f40b1ffd4941aed0646a0d8b3"),
        "24.19.0-linux_s390x": ("node-v24.19.0-linux-s390x.tar.xz", "node-v24.19.0-linux-s390x", "a4792e65962ffa0af42627aacf1122a60c3c88dbf4e4184f06820d66f9da8ba4"),
        "24.19.0-linux_amd64": ("node-v24.19.0-linux-x64.tar.xz", "node-v24.19.0-linux-x64", "14b342e71204f811bde6153be8e04b62aef63c236fef92b55f9c83154b409647"),
        "24.19.0-windows_amd64": ("node-v24.19.0-win-x64.zip", "node-v24.19.0-win-x64", "57f71ab3652e797d84acddc79c81cc9ff1c6ddb2a1974cdb83f00fee9bff4c73"),
    },
    node_version = "24.19.0",
)
use_repo(node, "nodejs_toolchains")

# JS
bazel_dep(name = "aspect_rules_js", version = "3.4.1")

pnpm = use_extension("@aspect_rules_js//npm:extensions.bzl", "pnpm")
pnpm.pnpm(
    name = "pnpm",
    pnpm_version = "11.24.0",
    pnpm_version_integrity = "sha512-vSfjRel23LC+C3oSKCF7BJqBfiGx81XJDb59xGZxiVqLwebQbCRVRQXqk+oLRfSJon7Bv7yN5qlln8oPFvoAAA==",
)
use_repo(pnpm, "pnpm")

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
npm.npm_translate_lock(
    name = "npm_rules_browsers",
    data = [
        "//:package.json",
        "//:pnpm-workspace.yaml",
    ],
    pnpm_lock = "//:pnpm-lock.yaml",
)
use_repo(npm, "npm_rules_browsers")

# TS
bazel_dep(name = "aspect_rules_ts", version = "3.10.1")

rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext")
rules_ts_ext.deps(
    # Specify a name manually to prevent conflicts in consumers that also use
    # `aspect_rules_ts`. This requires that we override the default for `tsc`,
    # `tsc_worker` and `validator` on all `ts_project` targets.
    # Upstream issue: https://github.com/aspect-build/rules_ts/issues/843
    name = "npm_rules_browsers_typescript",
    ts_integrity = "sha512-y2TvuxSZPDyQakkFRPZHKFm+KKVqIisdg9/CZwm9ftvKXLP8NRWj38/ODjNbr43SsoXqNuAisEf1GdCxqWcdBw==",
    ts_version = "6.0.3",
)
use_repo(rules_ts_ext, "npm_rules_browsers_typescript")
