name: 'Check Package Licenses'
description: 'Check all dependencies to confirm licenses are allowed'
author: 'Angular'

inputs:
  allow-dependencies-licenses:
    description: 'Any package(s) in purl format'
    required: false

runs:
  using: composite
  steps:
    - name: Check Package Licenses
      uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2
      env:
        # The action ref here allows us to import the config file from the same sha we rely on in the downstream usage
        ACTION_REF: ${{ github.action_ref || 'main' }}
        ACTION_REPO: ${{ github.action_repository || 'angular/dev-infra' }}
      with:
        config-file: '${{ env.ACTION_REPO }}/github-actions/linting/licenses/dependency-review-config.yml@${{ env.ACTION_REF }}'
        allow-dependencies-licenses: '${{inputs.allow-dependencies-licenses}}'
        show-openssf-scorecard: false
