vulnerability-check: false
allow-licenses:
  - '0BSD'
  - 'Apache-2.0'
  - 'Artistic-2.0'
  - 'BlueOak-1.0.0'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'CC-BY-3.0'
  - 'CC-BY-4.0'
  - 'CC0-1.0'
  - 'ISC'
  - 'LGPL-3.0'
  - 'LGPL-3.0+'
  - 'MIT'
  - 'MIT-0'
  - 'Python-2.0'
  - 'Unlicense'
allow-dependencies-licenses:
  # Renovate uses the AGPL-3.0 license, which we have determined is okay for our
  # usage. We do not however, want to depend on this license in general
  - 'pkg:npm/renovate'
