name: 'Slash Commands'
description: 'Handle slack commands in the repository'
author: 'Angular'
inputs:
  angular-robot-key:
    description: 'The private key for the Angular Robot Github app.'
    required: true
runs:
  using: 'node20'
  main: 'main.js'
