name: 'Checkout and Setup Node'
description: 'Checks out the repository and sets up node environment.'
author: 'Angular'
inputs:
  fetch-depth:
    default: 0
    description: |
      The number of commits to include in the fetch, defaulting to all commits in the history
      of the repository

  ref:
    description: |
      The branch, tag or SHA to checkout. Defaults to allowing actions/checkout to determine the ref.

  node-version:
    description: |
      A specific version of node to use for the node environment, exclusive with
      node-version-file-path input.

  node-version-file-path:
    default: '.nvmrc'
    description: |
      Relative path to the nvm version file to set node version, exclusive with
      node-version-file-path input. Defaults to .nvmrc

  cache-node-modules:
    default: false
    type: boolean
    description: |
      Whether to cache the node_modules directory, this is helpful when postinstalls are performed
      and modify the resulting node_modules directory. Defaults to False.

  node-module-directories:
    default: ./node_modules
    description: |
      Space delimited list of node_modules directories to cache. Defaults to `./node_modules`

runs:
  using: composite
  steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}
        persist-credentials: false

    - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        node-version-file: ${{ inputs.node-version-file-path }}
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'

    - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      if: ${{ inputs.cache-node-modules == 'true' }}
      with:
        path: ${{ inputs.node-module-directories }}
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock', '**/*.patch') }}
