name: 'Lock Closed Issues'
description: 'Locks issues that are both closed and inactive'
author: 'Angular'
inputs:
  lock-bot-token:
    description: 'A private key for the Lock Bot GitHub app'
    required: true
  locks-per-execution:
    description: 'Maximum number of issue locks per action execution'
    default: 100
runs:
  using: 'node12'
  main: 'lib/bundle.js'
