name: 'Manage Feature Requests'
description: 'Manages feature requests based on community demand'
author: 'Angular'
inputs:
  angular-robot-key:
    description: 'The private key for the Angular Robot Github app.'
    required: true
  minimum-unique-comment-authors-for-consideration:
    description: 'Number of unique comment authors required to move a feature request to our consideration list.'
    default: 10
  minimum-votes-for-consideration:
    description: 'Number of votes required to move a feature request to our consideration list.'
    default: 20
  feature-request-label:
    description: 'Label used to distinguish feature request from other issues.'
    default: 'feature'
  in-backlog-label:
    description: 'Label used to distinguish feature requests, which are already part of the backlog.'
    default: 'feature: in backlog'
  requires-votes-label:
    description: 'Label used to distinguish requests in voting phase from other issues.'
    default: 'feature: votes required'
  under-consideration-label:
    description: 'Label used to distinguish features which are in our list for consideration.'
    default: 'feature: under consideration'
  old-issue-warn-days-duration:
    description: 'Indicates in number of days how old an issue should be to directly get a warning comment rather than just a vote initiation.'
    default: 60
  warn-days-duration:
    description: 'Number days of after the voting has started to post the warning comment.'
    default: 40
  close-after-warn-days-duration:
    description: 'In what duration in days the bot should close a particular request if it has not collected enough votes or comments.'
    default: 20
  close-when-no-sufficient-votes:
    description: 'If set to true, the bot will automatically close the issue when voting has ended, if the request has not collected a sufficient number of votes. Alternatively, the bot will just add a `voting-finished-label`.'
    default: false
  insufficient-votes-label:
    description: 'Label to add when the `close-when-no-sufficient-votes` is set to false and there are no sufficient number of votes or comments from unique authors.'
    default: 'feature: insufficient votes'
  limit:
    description: 'Limits the number of issues we are going to run the action over.'
    default: -1
  close-comment:
    description: 'Comment to post when closing the issue.'
    default: >
      Thank you for submitting your feature request! Looks like during the polling
      process it didn't collect a sufficient number of votes to move to the next stage.


      We want to keep Angular rich and ergonomic and at the same time be mindful about
      its scope and learning journey. If you think your request could live outside
      Angular's scope, we'd encourage you to collaborate with the
      [community](https://angular.io/resources?category=community) on publishing it
      as an open source [package](https://angular.io/guide/creating-libraries).


      You can find more details about the feature request process in our
      [documentation](https://github.com/angular/angular/blob/e29eb8abfbfdfb793e08ac88e14b7ba6d2ff2136/docs/GITHUB_PROCESS.md#feature-request-process).
  start-voting-comment:
    description: 'Comment to kick voting off.'
    default: >
      This feature request is now candidate for our backlog! In the next phase, the community has 60 days to
      upvote. If the request receives more than 20 upvotes, we'll move it
      to our consideration list.


      You can find more details about the feature request process in our
      [documentation](https://github.com/angular/angular/blob/e29eb8abfbfdfb793e08ac88e14b7ba6d2ff2136/docs/GITHUB_PROCESS.md#feature-request-process).
  warn-comment:
    description: 'A warning that the end of voting is approaching.'
    default: >
      Just a heads up that we kicked off a community voting process for your feature request. There are 20 days until the voting process ends.


      Find more details about Angular's feature request process in our [documentation](https://github.com/angular/angular/blob/e29eb8abfbfdfb793e08ac88e14b7ba6d2ff2136/docs/GITHUB_PROCESS.md#feature-request-process).
runs:
  using: 'node20'
  main: 'main.js'
