name: 'Config saucelabs'
description: 'Set saucelabs environmental variables'
author: 'Angular'

runs:
  using: composite
  steps:
    - run: node $GITHUB_ACTION_PATH/set-saucelabs-env.js
      env:
        NGAT: ${{ secrets.SAUCELABS_NGAT }}
      shell: bash
