name: 'Setup Bazel remote execution'
description: 'Sets up Bazel remote execution.'
author: 'Angular'
inputs:
  bazelrc:
    default: '.bazelrc.user'
    description: |
      If specified, the given `bazelrc` file is being updated to always run
      with the `--config=remote` flag. Defaults to `.bazelrc.user`

runs:
  using: composite
  steps:
    - uses: google-github-actions/auth@55bd3a7c6e2ae7cf1877fd1ccb9d54c0503c457c # v2.1.2
      with:
        project_id: 'internal-200822'
        workload_identity_provider: 'projects/823469418460/locations/global/workloadIdentityPools/github/providers/angular'
        service_account: bazel-developer@internal-200822.iam.gserviceaccount.com
    - run: node $GITHUB_ACTION_PATH/configure-remote.cjs
      env:
        BAZELRC_PATH: ${{ inputs.bazelrc }}
      shell: bash
