name: 'Setup Bazel remote execution'
description: 'Sets up Bazel remote execution.'
author: 'Angular'
inputs:
  bazelrc:
    default: '.bazelrc.user'
    description: |
      If specified, the given `bazelrc` file is being updated to always run
      with the `--config=remote` flag. Defaults to `.bazelrc.user`
  only_cache:
    default: false
    description: |
      Whether to only set up remote caching, instead of allowing for full
      remote execution (on Linux/macOS).

  shell:
    default: bash
    description: Shell to use for executing the configure script.

runs:
  using: composite
  steps:
    - run: node $GITHUB_ACTION_PATH/configure-remote.cjs
      env:
        BAZELRC_PATH: ${{ inputs.bazelrc }}
        ONLY_CACHE: ${{ inputs.only_cache }}
        NGAT: 'bKddxrYADouso3haW7lCFA=='
      shell: ${{ inputs.shell }}
