name: DevInfra

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  breaking_changes_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./github-actions/breaking-changes-auto-labeling
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
