name: Angular-Org Renovate

on:
  workflow_dispatch:
  schedule:
    # Runs every 30 minutes.
    - cron: '*/30 * * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  renovate:
    strategy:
      matrix:
        REPOSITORY:
          - angular/angular
          - angular/dev-infra
          - angular/components
          - angular/angular-cli
          - angular/ai-tutor
          - angular/web-codegen-scorer
    runs-on: ubuntu-latest
    steps:
      # Because the checkout and setup node action is contained in the dev-infra repo, we must
      # checkout the repo to be able to run the action we have created.  Other repos will skip
      # this step.
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./github-actions/npm/checkout-and-setup-node
        with:
          cache-dependency-path: './.github/ng-renovate/pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile
        working-directory: ./.github/ng-renovate
      - name: Setup UV
        if: matrix.REPOSITORY == 'angular/web-codegen-scorer' # UV is only needed for web-codegen-scorer as it uses python.
        uses: astral-sh/setup-uv@6ee6290f1cbc4156c0bdd66691b2c144ef8df19a # v7.4.0
      - name: Setup Dart
        if: matrix.REPOSITORY == 'angular/dev-infra' # Dart is only needed for rules_sass which is in dev-infra.
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1
      - run: pnpm exec renovate
        working-directory: ./.github/ng-renovate
        env:
          LOG_LEVEL: debug
          RENOVATE_TOKEN: ${{ secrets.NG_RENOVATE_USER_ACCESS_TOKEN }}
          RENOVATE_FORK_TOKEN: ${{ secrets.NG_RENOVATE_USER_ACCESS_TOKEN }}
          GITHUB_COM_TOKEN: ${{ secrets.NG_RENOVATE_USER_ACCESS_TOKEN }}
          RENOVATE_CONFIG_FILE: ./runner-config.js
          RENOVATE_REPOSITORIES: ${{ matrix.REPOSITORY }}
