name: Performance Tracking

on:
  push:
    branches:
      - main

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  workflow-perf:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      # Because the checkout and setup node action is contained in the dev-infra repo, we must
      # checkout the repo to be able to run the action we have created.  Other repos will skip
      # this step.
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./github-actions/npm/checkout-and-setup-node
      - uses: ./github-actions/bazel/setup
      - run: yarn install --immutable
      - run: yarn ng-dev perf workflows --json
