name: Performance Tracking

on:
  push:
    branches:
      - main

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  list:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    outputs:
      workflows: ${{ steps.workflows.outputs.workflows }}
    steps:
      # Because the checkout and setup node action is contained in the dev-infra repo, we must
      # checkout the repo to be able to run the action we have created.  Other repos will skip
      # this step.
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./github-actions/npm/checkout-and-setup-node
      - uses: ./github-actions/bazel/setup
      - run: yarn install --immutable
      - id: workflows
        run: echo "workflows=$(yarn ng-dev perf workflows --list)" >> "$GITHUB_OUTPUT"

  workflow:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: list
    strategy:
      matrix:
        workflow: ${{ fromJSON(needs.list.outputs.workflows) }}
    steps:
      # Because the checkout and setup node action is contained in the dev-infra repo, we must
      # checkout the repo to be able to run the action we have created.  Other repos will skip
      # this step.
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./github-actions/npm/checkout-and-setup-node
      - uses: ./github-actions/bazel/setup
      - run: yarn install --immutable
      - run: yarn ng-dev perf workflows --name ${{ matrix.workflow }}
