name: Rebase PR

on:
  pull_request:
    types: [labeled]

jobs:
  rebase-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: App Auth
        if: github.event.label.name == 'rebase-pr'
        id: authenticate
        uses: ./github-actions/app-auth
        with:
          app-id: 43341
          installation-id: 2803773
          private-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
      - name: Rebase PR
        if: github.event.label.name == 'rebase-pr'
        uses: ./github-actions/rebase-pr
        env:
          TOKEN: ${{ steps.authenticate.outputs.installation_access_token }}
