name: Rebase a pr

on:
  pull_request:
    types: [labeled]

jobs:
  rebase_pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@master
      - name: Rebase PR
        if: github.event.label.name == 'rebase-pr'
        uses: angular/dev-infra/github-actions/rebase-pr@master
        env:
          TOKEN: ${{ secrets.ANGULAR_REBASE_BOT_TOKEN }}
