name: Rebase PR

on:
  pull_request:
    types: [labeled]

jobs:
  rebase_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: App Auth
        id: authenticate
        uses: ./github-actions/app-auth
        with:
          app-id: 43341
          installation-id: 2789539
          private-key: ${{ secrets.GITHUB_ROBOT }}
      - name: Rebase PR
        if: github.event.label.name == 'rebase-pr'
        uses: ./github-actions/rebase-pr
        env:
          TOKEN: ${{ steps.authenticate.outputs.installation_access_token }}"
