name: rules_sass Compiler Binaries Update

on:
  schedule:
    # Runs at minute 0 of every 6th hour (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows you to trigger it manually.

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            bin_name: sass_linux_x64
          - os: macos-15-intel
            bin_name: sass_mac_x64
          - os: macos-latest
            bin_name: sass_mac_arm
          - os: ubuntu-24.04-arm
            bin_name: sass_linux_arm
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: bazel/rules/rules_sass
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1
      - run: dart pub get --enforce-lockfile
      - run: mkdir -p src/compiler/built/

      # To fix the non-deterministic build problem on macOS, force the Dart compiler to use a stable,
      # non-random temporary directory during compilation. By default, macOS uses a random subfolder in /var/folders/...,
      # but we can override this by setting the TMPDIR environment variable to a fixed path within the workspace.
      - run: |
          mkdir -p .dart_tmp
          export TMPDIR="$(pwd)/.dart_tmp"
          dart compile exe src/compiler/bin/x_sass.dart -o src/compiler/built/${{ matrix.bin_name }}
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ matrix.bin_name }}
          path: bazel/rules/rules_sass/src/compiler/built/${{ matrix.bin_name }}
          retention-days: 1

  create_pr:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bazel/rules/rules_sass
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - run: mkdir -p src/compiler/built/
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: bazel/rules/rules_sass/src/compiler/built/
          merge-multiple: true
      - name: chmod binaries
        run: chmod +x src/compiler/built/*
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.ANGULAR_ROBOT_ACCESS_TOKEN }}
          push-to-fork: 'angular-robot/dev-infra'
          delete-branch: true
          maintainer-can-modify: true
          branch: compiler-binary-updates
          committer: Angular Robot <angular-robot@google.com>
          author: Angular Robot <angular-robot@google.com>
          title: 'Update compiler binaries to latest version'
          commit-message: 'build: update rules_sass compiler binaries to latest version'
          body: |
            Updated Sass compiler binaries.
          labels: |
            action: merge
