name: rules_sass Compiler Binaries Update

on:
  schedule:
    # Runs at minute 0 of every 6th hour (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows you to trigger it manually.

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-15-intel, macos-latest]
        include:
          - os: ubuntu-latest
            bin_name: sass_linux_x64
          - os: macos-15-intel
            bin_name: sass_mac_x64
          - os: macos-latest
            bin_name: sass_mac_arm
          - os: ubuntu-24.04-arm
            bin_name: sass_linux_arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1
      - run: dart pub get
      - run: mkdir -p bazel/rules/rules_sass/src/compiler/built/
      - run: dart compile exe ./bazel/rules/rules_sass/src/compiler/built/x_sass.dart -o bazel/rules/rules_sass/src/compiler/built/${{ matrix.bin_name }}
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: ${{ matrix.bin_name }}
          path: bazel/rules/rules_sass/src/compiler/built/${{ matrix.bin_name }}
          retention-days: 1

  create_pr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - run: mkdir -p bazel/rules/rules_sass/src/compiler/built/
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          path: bazel/rules/rules_sass/src/compiler/built/
          merge-multiple: true
      - name: chmod binaries
        run: chmod +x bazel/rules/rules_sass/src/compiler/built/*
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.ANGULAR_ROBOT_ACCESS_TOKEN }}
          push-to-fork: 'angular-robot/dev-infra'
          delete-branch: true
          maintainer-can-modify: true
          branch: compiler-binary-updates
          committer: Angular Robot <angular-robot@google.com>
          author: Angular Robot <angular-robot@google.com>
          title: 'Update compiler binaries to latest version'
          commit-message: 'build: update rules_sass compiler binaries to latest version'
          body: |
            Updated Sass compiler binaries.
          labels: |
            action: merge
