"""Available versions of "chromedriver".

DO NOT EDIT. Generated by //browsers/private/update-tool:update-tool.
"""

DEFAULT_VERSION = "147.0.7687.0"

VERSIONS = {
    "128.0.6613.137": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.137/linux64/chromedriver-linux64.zip",
            "integrity": "f041092f403fb7455a6da2871070b6587c32814a3e3c2b0a794d3d4aa4739151",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.137/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "52d049646fa945dab0c56b2fbb162b449b2615d3046b987a9565eddfd70fc45d",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.137/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "d8716b23073c273960ebf78a909a9f77c9304bc73aa68c14d919e904631205a9",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.137/win64/chromedriver-win64.zip",
            "integrity": "c383fefbf5d50b4d6283cf0a06b758163645c1293c9c1209bdc3ae07aa102dde",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "129.0.6668.100": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/linux64/chromedriver-linux64.zip",
            "integrity": "91f64cd4c61814b0464687fe7ab97a854b9aaaa17f523974b7d9848b0ec1f9f9",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "0221009086f8b541c31a00d315d91dc4cf003e06b05024d8a265dd0493185c4e",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "258b8d65583407c19ab83a57601a67ad4ea02caf177af1c123cba8641d4928fb",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/win64/chromedriver-win64.zip",
            "integrity": "14e3b0f347b8a8c9c15276f5de2be2db494c67c58fc47e0cd43569142d00da4d",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "130.0.6723.116": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/linux64/chromedriver-linux64.zip",
            "integrity": "35b6751942cb589e8bde4733cf6dc7a1484693a56004e5dc8d994beede19e847",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "f8f71dfbed7dfe7255b2a1abda3cf28cc4d661f6f653dc1282735c703c86b865",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "beb6c8a47ac1c1bcea6abb3b0f9e3a789ef384484007469babb3178aa954e2db",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/win64/chromedriver-win64.zip",
            "integrity": "6944d3da40f1d886b559b8f57e74ee6ac2767da49d3c0654a8f9ecf113e15bd8",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "131.0.6778.264": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/linux64/chromedriver-linux64.zip",
            "integrity": "3d65a0af6d016367bc059813881c237a5b5077333906808416df3f861d1eec3e",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "753d02a4eff922b7dc832f4fe0153b4ae588dd8fb4f9b817b3769973b6df81b1",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "a495f2bc534453f7a8ab0c21b8233d625751049822c011173a63e255a7c2c529",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/win64/chromedriver-win64.zip",
            "integrity": "8f8eafbf4337e53b94b79163e251ca0380fd7597cc875af71c79ff37376cd466",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "132.0.6834.159": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/linux64/chromedriver-linux64.zip",
            "integrity": "13930d2b5e5f69d15c206556bd66e623aa325d03edde091b169b7cc5f7880e3e",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "50639151eaff168e7a55325120e11ceaa4b0cdedb5bb6df65511319f064dac2f",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "8c4f819045397f2c969da9e0ba9468d63101405c971e4592a09121269b89a7d0",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/win64/chromedriver-win64.zip",
            "integrity": "18f998efb2cc95be45fd7bf7f2ef5344de1003756d27c6be61360b187303e2e5",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "133.0.6943.141": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.141/linux64/chromedriver-linux64.zip",
            "integrity": "d3826586626a8e91d8b1d2da76423e2b4fd7179148284afe4677c72dcd0f1a27",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.141/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "d1964c4b4381c76367af53ce87d304e1586bf7d0d767b7ceef86cb651120c4eb",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.141/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "b72a618ac15de86cb622421b5442056bf4c19a79d834a2894c2c390b54aba3de",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.141/win64/chromedriver-win64.zip",
            "integrity": "deea4e23cbd37f98a5decb72c47cee7df556448812803c2704ee8e415c60763e",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "134.0.6998.165": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/linux64/chromedriver-linux64.zip",
            "integrity": "f45902a1b61ae4e5741c468286677213c6376fd6543b0809b94a84e6f7fc17f8",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "4e5ff9ecbe1586e4820784e532b25c33eec0304f7699919d59d2888a4f49b95c",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "75e95741d120626ea3fa4ac975e7415cb55aa784a7e8e6c27c5255e43545c991",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/win64/chromedriver-win64.zip",
            "integrity": "524b0fd07c7cc7182082bc4fc59a4fd35c64c1e10c279bcfe608645cde185b0b",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "135.0.7049.114": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/linux64/chromedriver-linux64.zip",
            "integrity": "28ef94323503f927f8fca4650d5acf6325e69829720900cc696c3d8179ce855c",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "a1da3421971762c4d6f258fb8e49dfd3aa855387f0b82d0333a59e972feb21d9",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "483f4f09b41d93a47afe429910b86b745ba941209360da1d45d213dc6475c440",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/win64/chromedriver-win64.zip",
            "integrity": "e52c931bda47bb5510e46a8bab9e4ec5c54a16072e5dfa359e550a64675be451",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "136.0.7103.113": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.113/linux64/chromedriver-linux64.zip",
            "integrity": "121e7af496671aec492ac910d192446c3038d565f8be93e1eaaef7b113f4ce8c",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.113/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "171e8df024bb23c9078d971d5f6302a7946b1f53400368b934b1ba1de0074eaa",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.113/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "8c8a6956b93dc2ccbbc2d1146fa99da0af507c291567d421570e9912e91d2189",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.113/win64/chromedriver-win64.zip",
            "integrity": "d75e1179862c37fb7cae21f0aa38a635bf596d11d2137597f8552c04db9d62af",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "137.0.7151.119": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.119/linux64/chromedriver-linux64.zip",
            "integrity": "f4138b39e4fbe948e887ed5c1e0286c539fa81657cd5f2d8d51c1f68921a8880",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.119/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "3502bec185bbb2732f21648d02ed3ac3c478ddfa35f3deddc9cc1433335309b7",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.119/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "dbb01e0ac438d29cfbfeffbf0321e07afb099edc4a472ecedaa55202da5385fe",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.119/win64/chromedriver-win64.zip",
            "integrity": "6d0098a2da09f330982e4df8d973e83725f22be5f6df8614e87196b3bcbf3017",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "138.0.7204.183": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.183/linux64/chromedriver-linux64.zip",
            "integrity": "7b5e09e535063fb49237aa0dd465e9f914b23517a7379fb6de28c918f833a62d",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.183/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "47d8ecf55eb091e53b12b70a37cfb35df282c55c01488d6b03169c7fe07dc983",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.183/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "7a09dc603b366523d8bb21316e620ee093d3c4e944d428a7e5922e8464a22ba1",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.183/win64/chromedriver-win64.zip",
            "integrity": "b1aba8697f8412bed9e7a7d054819e8cce8c5d13553d9f274ccb1df66c884315",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "139.0.7258.154": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/139.0.7258.154/linux64/chromedriver-linux64.zip",
            "integrity": "0b8e3924c2087cbe94e7bad27e7084ab908aeb53441a4e5a7f1f01c0b82a875e",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/139.0.7258.154/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "949505cb45f015607dd2e0e56d89f4f4c8415a51dc41d97c20b60d78af6caabc",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/139.0.7258.154/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "842abfd280e701161bc8c3c66934b63ab51a64722fd331e142950a8ee1314c85",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/139.0.7258.154/win64/chromedriver-win64.zip",
            "integrity": "5e5072172e734be29d3160c88fae4f61618f39bdcd804bf3eacac995ced7a432",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "140.0.7339.207": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/linux64/chromedriver-linux64.zip",
            "integrity": "565ed161013222184786b7e7667953d9d978cd4566c51b2b179c7fecd52759c3",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "f3a0ba58a37a7f37907cfbbb0d92a26b7daf3a9eaec0641a4f2328b17f2cda4d",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "6a1022d96f70475a7e75861b6ee4d6c1b0a81dd6fb8f6043d963f3153caa0722",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/win64/chromedriver-win64.zip",
            "integrity": "7e03ad80e47f43738320ea3ee6703c3b62a1a20ddfb96dcdabb8aba283a2ee59",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "141.0.7390.54": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.54/linux64/chromedriver-linux64.zip",
            "integrity": "98b142a6342b8481084876a4e6747a291762641d9016b10c0178a24959fb6d03",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.54/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "1140ed8fa9408c09968823ce20703b1303500789b6ce334056635eb477591dca",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.54/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "8bb230583fe2e235c02575b8503e8635125cbe86882739b15d1460ee101b80d8",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.54/win64/chromedriver-win64.zip",
            "integrity": "04ca20c2581160ea4b0f4989883328abfa77aabd95a3755326da4d8242721e20",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "141.0.7390.65": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.65/linux64/chromedriver-linux64.zip",
            "integrity": "eabcd234f516bb85ceeeb9368f694a3b7d3b3f2002d37f2a986f1a212bc9f696",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.65/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "8776657e5718701f9f13740e04efbcff1cb08bcfccc7d459d88008775c05d9e6",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.65/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "08cfb5203050823091bfa6fa116d3d4934719a897c4dc3d9a01c96d26fddbaa4",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.65/win64/chromedriver-win64.zip",
            "integrity": "3f408a173d87d979a7ced93e5556dac4a1bff228d4f697dff130ad2d6856e175",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "141.0.7390.78": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.78/linux64/chromedriver-linux64.zip",
            "integrity": "91766fb286e64a2af8bf3356c43f2c316f61c2ee0b7c8aab634df3f8437b5c48",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.78/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "2ed6bb0d416aeb81eea785fcb8e6b94f5d721300052907968ec5b2383b75ff17",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.78/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "9cc390d9f9db3da35ffb16dea9a509a980ee63a61c267a4456b5cbd9373b04e3",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.78/win64/chromedriver-win64.zip",
            "integrity": "fc01f94897391cfbc875293676a3da15ca455b7df6f7236296eb10bbe54423a8",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "141.0.7390.122": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.122/linux64/chromedriver-linux64.zip",
            "integrity": "38337a39540faa6171b51578414ced223b6b39d66badd571280a5c6f932596ce",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.122/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "ccb0000fea8263973d839d40be51dfe8488fbe9364c7c78bc03ae14a73bfa001",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.122/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "23ff577ca01f74aba74c1bf4c4667da41cfd37ac5095cdefe77aa4b555e12969",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.122/win64/chromedriver-win64.zip",
            "integrity": "e6534e7d7aedd787bc4704e2fd29581bb72c4e9f33f08ae3dc12740162b6957d",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "142.0.7444.6": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.6/linux64/chromedriver-linux64.zip",
            "integrity": "da19a48eca2e7a09d757003eda2e814c8b7a9db462301faccc24564e5e593eca",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.6/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "156dc49c7f1707c72b670182d63fc2e6414734950221ba5c2fc133f580ed3713",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.6/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "83cd191d57d4d841a761b2bbd42d29d5df6b748c510ad474e3d0a17ca46929ae",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.6/win64/chromedriver-win64.zip",
            "integrity": "8b1cad695e78e1a68055680f411eb65c5d305d2d3dadc1b60fdaf73ea373fc22",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "142.0.7444.34": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.34/linux64/chromedriver-linux64.zip",
            "integrity": "33850b3337bc92c6621e013af03323e0d6ae1e450aa1ff6b5776d47dd4d9b600",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.34/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "840101066642b930b937ba5e8d7506d9a71bbb6a9a45b5a4c11c05d83aace12c",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.34/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "eb8c32d19b7cf56fbb8aa5e1f1cf57170787d3eda59b9d4b6c7b93f09428bd92",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.34/win64/chromedriver-win64.zip",
            "integrity": "93daa4027ad50b85fbcaafbe28b1b25d7afe56cf99f2fd20ebee023ee8c14a5a",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "142.0.7444.175": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.175/linux64/chromedriver-linux64.zip",
            "integrity": "2a859045e176e8af4ab2daca73f6f2e41937f37fecaecef3c9e78cc8fa9ecad7",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.175/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "40bf1e10a4722a6fe7c40aeed14f530fcd08a8ce0d7a04df393ac35f9bde1ae8",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.175/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "300de6ec605f161ab8a334dd239a5135d539347fc6745f802c881cb6e5091ebc",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.175/win64/chromedriver-win64.zip",
            "integrity": "e05b2c2e451d0ad2a191a61f2db45ffab770e9335d38ed684f2255d75a76daee",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "143.0.7459.0": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7459.0/linux64/chromedriver-linux64.zip",
            "integrity": "8bf018ed7c383dfd4a4a8f26702265e58b053e71583c4b7a6f8a3eaa6e9b9e6f",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7459.0/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "4eb9cc848823444374bf2d3d388eaa949cee92114a611ce850024bf6b91352d1",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7459.0/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "13f142a6c53f38d26552ee21a874e3d11497bf6fb580b79a6b6b4b042875bef6",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7459.0/win64/chromedriver-win64.zip",
            "integrity": "65c25dfbe56801d342ae027f365194d0d5b31602ec94e644fe21b6edb876904a",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "143.0.7482.0": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7482.0/linux64/chromedriver-linux64.zip",
            "integrity": "ea41e7a217d878c00e9d66a0724ff54be7d02d08adb7f6458b7d8487b6fbcd84",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7482.0/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "aede9b67301b930ff9c673df28429aa82ce05c105a4ccbef7e0cd30a97ae429d",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7482.0/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "5adf89a3e8edc6755920f4cfe2fe0515d40684878ef5201da5e02a9d491c4003",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7482.0/win64/chromedriver-win64.zip",
            "integrity": "a3dfe62b3e9e7a42bd324c07dcbbcc3a733a736b2a59f0e93b9250b88103ab73",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "143.0.7499.25": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.25/linux64/chromedriver-linux64.zip",
            "integrity": "65b45fab45851dec6895e045d195a1673736fddb6449250974afa397f3d4d991",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.25/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "8e0c0fbd15e7fd6b6a9e810b1eb0a9bd12d026d50f4e2f47299e817573bb0676",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.25/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "1b9e34b997d699b7ca4653cd0443e073165ce2bc4875582ba4fe329830589ed4",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.25/win64/chromedriver-win64.zip",
            "integrity": "d9c1f476b10fe8c1b3944c242fa92a5596e06abb27917ed47a94bdaa52a703b9",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "143.0.7499.169": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.169/linux64/chromedriver-linux64.zip",
            "integrity": "9739384a5a92d5308c85dba47fdf38edf67b599110fbfd7846aaf9eeace0d25d",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.169/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "06342aca51f5ab5e9a5f2858d9953dadb52e29e5cfcb0229d1ab1a989ebc6be2",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.169/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "1635bac913afe40f5b4d22ee03848f39904a39a7d4fd062532cd832ed001a73f",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.169/win64/chromedriver-win64.zip",
            "integrity": "eafe9deb3c05c0af107a55a0e354fcaaf7dbb11ed8b77ccaaf7b0412f71b1374",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "143.0.7499.192": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.192/linux64/chromedriver-linux64.zip",
            "integrity": "43f852cef783a1ce31f8a5a0d8f45f5863625e9bfdba69ef39f871a8c7358123",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.192/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "2e104f71d6bc9e28cb475ae3f7cd5d4e475dde130cd28af7e23ab58c4dce4d74",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.192/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "30f79f97d3a3cd391b459694b718b4b90524e1f15e0aeb47d59d13fa9a7372ee",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.192/win64/chromedriver-win64.zip",
            "integrity": "41a63b585bd90c6b48c061070c1b4ea8b8b1b0558fa7a3be81159dc5857d0581",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "144.0.7531.0": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7531.0/linux64/chromedriver-linux64.zip",
            "integrity": "baf4bf9d22881265487732f17d35a49e9aadd0837aa5c1c1eea520c8aa24a97f",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7531.0/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "87560768d5aa203b37c0a1b8459a35b05e4ece54afee2df530f3bc33de4f63c5",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7531.0/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "99821795fa7c87eb92fb15248e23b237c83f397486d22ad9a10771622c36a5a0",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7531.0/win64/chromedriver-win64.zip",
            "integrity": "6e180e234a710c3cbf69566f64a662ed85473db6ae82275fd359f80ab288df99",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "144.0.7559.31": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.31/linux64/chromedriver-linux64.zip",
            "integrity": "fbd15841f865e6b6697711331aaecb0b3c3c3e1df5f963989830336bf5b6ab90",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.31/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "eab345eaf4255430b62cebfb3f4728c3b8468f85a4a61f90eae550aa4dad6048",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.31/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "be9525554cb863f6391c7b2bdbf95b95dc8b73cd6e42a692806b953d639255ff",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.31/win64/chromedriver-win64.zip",
            "integrity": "abac197e5e7fd8960f28f5f392125d8e8bf918135fc3d1f6c5579b156e2b1bb9",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "144.0.7559.133": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.133/linux64/chromedriver-linux64.zip",
            "integrity": "4b27e92604394d5f716cca15dac40f587e6b63cf9233f4e01e80507af3f0936a",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.133/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "70001d0f17a7e89ecfabee5448ddba82be94e54c50d7b6dc3d2baf7881b9259d",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.133/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "4d1d5c99f1d89d7f2dd09de2b0b0d570ec1093aa343b3a85d2abbbac79396c11",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.133/win64/chromedriver-win64.zip",
            "integrity": "159e928bd3aa31e99ae71db42701e9d80bceaa016eb2b10da15488d9e983daad",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "145.0.7586.0": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7586.0/linux64/chromedriver-linux64.zip",
            "integrity": "69c504306399d979a2766fea603c3fb9d3d87d46c75bddc9f2a049b4f636d57c",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7586.0/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "5fc9d6f594fc5f2568a15145f25116dd8e9c9a60baa8da4bb21a17650fb00e7e",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7586.0/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "14e92294c2c3639ca4e7d27e850588b619d698e2f8905cee368f07db2e1bf1e9",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7586.0/win64/chromedriver-win64.zip",
            "integrity": "cf641d2e176db95bcc158cd90eafd347ad4928fa0458a5f3bfd56c6d983e70db",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "145.0.7632.76": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7632.76/linux64/chromedriver-linux64.zip",
            "integrity": "b488306e608ec09e6b1376eab36639be0e82424f42865357abb97b164935b642",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7632.76/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "c6abcd8e17fc630f3797a50a3acdff93ec642af88c7584da823d465d49f5c19b",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7632.76/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "7d6a50291232bc9291a7a48f57d5574bd580fa7d612207744d811b9981d002b8",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7632.76/win64/chromedriver-win64.zip",
            "integrity": "06811e4ae9282cd588aa6ea00319ca4b3cc9c7b6f2e856429691d7f5efe95c3d",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "146.0.7680.4": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/146.0.7680.4/linux64/chromedriver-linux64.zip",
            "integrity": "531e72934c815ef2f4bf72719c786dd5d987f8cbb217a8faa6c527bbaf99c554",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/146.0.7680.4/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "9fc9d2bd60b442787575eb2d952918474b815a2cc198b92ae2d70822d4e0cb01",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/146.0.7680.4/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "9fc42d3f726fe9139093e5fa33516c0e64f3f59de8fa809cc049ff2e8fe48ff0",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/146.0.7680.4/win64/chromedriver-win64.zip",
            "integrity": "ac5ce8adb1377928ee1d2ffc9b05e881b5faee3d7446fd6fa6b772d3c9ae8156",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
    "147.0.7687.0": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/147.0.7687.0/linux64/chromedriver-linux64.zip",
            "integrity": "0607ccf6810a07ae08cac6443beac8b23f88dd53c7f1e0299e22d65f7cd2d020",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-linux64/chromedriver",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/147.0.7687.0/mac-x64/chromedriver-mac-x64.zip",
            "integrity": "0f512a9dd683ed4c41e609d8d02c07807497dbad3ab2f95f0d583486be7b8cff",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-x64/chromedriver",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/147.0.7687.0/mac-arm64/chromedriver-mac-arm64.zip",
            "integrity": "7d6fc6d17de1733eb6739d1ea16d085c8df1568bcf9fa0d130c2784b27f38268",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-mac-arm64/chromedriver",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/147.0.7687.0/win64/chromedriver-win64.zip",
            "integrity": "f4e9fb7bbf692fde7979b24e8d737b3cef4baafbc7a370e5d0abc4a8450fd830",
            "exclude_patterns": [],
            "named_files": {
                "CHROMEDRIVER": "chromedriver-win64/chromedriver.exe",
            },
        },
    },
}
