"""Available versions of "chromium".

DO NOT EDIT. Generated by //browsers/private/update-tool:update-tool.
"""

DEFAULT_VERSION = "147.0.7687.0"

VERSIONS = {
    "128.0.6613.137": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.137/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "ab945ee7dd4a86ff0eed01f48ef712e159066e9690259cbf275040f575c6cccd",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.137/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "42bb91660a3c5d31cbc06eab5080afb2d631f759de711f09a069a17a9f4a86a2",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.137/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "8a230d16b93ae37aaf48d13abf7367b21b057a29bdedfbfd544cc19adc59b1fa",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.137/win64/chrome-headless-shell-win64.zip",
            "integrity": "60c7148e42fa36085c4903f91c06cbeba99a3a56c2f6f479b8f4b5508ca20297",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "129.0.6668.100": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "2525e51e13fac1106e3d86e8a591d69341232b881b17f781803520afd89e178c",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "179ab4d0712c9328920e6531c7cf01a862855160d1164de3ef6fd52cd533848e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "37354477a36d6110642351633fee27dd0d45c689f4a2034d7a1455896da1eae9",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/win64/chrome-headless-shell-win64.zip",
            "integrity": "29e8c023ba63ec47debbdd359d977ab70414a2c168506ebce9936313bd1f022a",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "130.0.6723.116": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "686efe6dcfba3741d822adecb31da561d7be9fa8a0ff32cf260ff287380ad3a5",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "9ba7ec2c2a5cdf6025c50719ad96119f73f6a39f2513eb957eaa3568de01863e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "91f0c30299bfb422a3a40f3f043111e928b37c75f7befbaf137a39faff82f8cb",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/win64/chrome-headless-shell-win64.zip",
            "integrity": "8f381cb17452daff6b9c15b3152f1e3e696a366c697e32fd67db3a05a5d87ab6",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "131.0.6778.264": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "9a8014dbdc8a35e76949ccdfa2c13fafb93d2cc234bbee2cc40312d97328fd0f",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "15cc329db4b7151373954c08d500480c0215ab7a04fa098d6daa6374d5516589",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "eb1a3f5a4119a72630b9454ad86cbad29f0a5af0749ad8955077e49e43dbbd1b",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/win64/chrome-headless-shell-win64.zip",
            "integrity": "83720edec5a520fd4b7592c0f004c850480368f89501a6ab26da5b1942e67e9c",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "132.0.6834.159": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "1dd8c80b22b7c04a5339f7c4ca1b08ce2e8841c35aa1a6d1d3927d552dcbe900",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "ad7a3246326ea08bf9930bc175d97781014367382fb2fe69cc84c4abd60e442e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "fbf7b62161984cb42d1c80fc226b8e1106711c6970be62f1d4c1a5d073cbc743",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/win64/chrome-headless-shell-win64.zip",
            "integrity": "3e7a9cc5b55ed4731b602db66b27368aa87f3e68df649b7129af29a306573248",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "133.0.6943.141": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.141/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "cec67d7e4baf84814a8602ea59aa07a669f31d95e63e935b5e7b39e5986895a2",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.141/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "b7a12980ae2e0563f0d36119a078aec2e78d0fdc8c4b14f02be24c58a027d3f8",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.141/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "18c395d2d4e469c713e55f2d362ad5a46b8629885bd2a69576010f95bf95d3ae",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.141/win64/chrome-headless-shell-win64.zip",
            "integrity": "16a32d2c61754705ad73cb6d920e19198562cf9c58fe4723df2812c244beca13",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "134.0.6998.165": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "cda318dcbf2cccb89ce48dc4a65add41510323972c829b7df18a6acbaf0de573",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "e285ed8f82c97b3759e509c166e3ff54e5a868356db8315874954d25cb3fff4d",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "f486978f6d20f19d7071c6367933864a553174b8a5c22a5b7f195d8b73cb9fdd",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/win64/chrome-headless-shell-win64.zip",
            "integrity": "cc5dfbe337724e6141586a9a5ef76028f1bd1192d67c65471e5a79cd1afd0374",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "135.0.7049.114": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "edc2f6118c68f3c369f0dde3c2c31e400806308ab02ba3e2901e742212246e2e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "d11d798ee9d88e58e472dde5848e9766bd9334520b93cc76d4a657a8c5e09394",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "8d5e637de58362ecd260587e986419c7dc19a5dfebf1900611313a7f70169a5e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.114/win64/chrome-headless-shell-win64.zip",
            "integrity": "cd2d3906c8029e4c0b0f74376d78750e961f2a4b4a4a85c6cd9ead6b0858b5df",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "136.0.7103.113": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.113/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "484778f66466a0d179d16e3e2de66e4efbcd3b24bed0d2fc0864f43d68d46efa",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.113/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "8d1c97da2c20a774d2f13f0b8ae3446ef73c4a2d5c59caebdf2568192d127fb7",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.113/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "59215e859f0f665518273cc72f9ff293ef948d11021e9adef9aa6166bf0b3ccf",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.113/win64/chrome-headless-shell-win64.zip",
            "integrity": "5891697b505ee2c732c984d648291aeb296826a0315a6a36a6928309936dda70",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "137.0.7151.119": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.119/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "9dc00173ad9d156ada860b51fb4f91abe5563e7ebb84bb09c237e44f5f741c91",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.119/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "530489da62d26e89de598b6971fd34d45c1b9a0b02f65d09bdfe251ed9f20811",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.119/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "bb970ac1288c9141fa362daffcd0f49c82613d2f2ed4deafd792f30750192b94",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/137.0.7151.119/win64/chrome-headless-shell-win64.zip",
            "integrity": "f04d4655ea38b0eb26e770eadfa3a330694e3468e4753e107a94e0ccdb6c8458",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "138.0.7204.183": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.183/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "0b255a51ec03b8762da532741c10a2d858a8ecf7dc26a57a1bb137f50551845b",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.183/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "4c54c6187023692f0a8db1aa4a42496f6c0396464f46e00962f5c16ccc194c46",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.183/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "3af5c746bbd157c878986535b80760f62dd05199e15be938aa71b88cab803d30",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.183/win64/chrome-headless-shell-win64.zip",
            "integrity": "560b2829a691e3299ae11787dd22b9a5aca032667f50fc455c4b7b4e6f3916ae",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "139.0.7258.154": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/139.0.7258.154/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "8551dcb89673980616528b0af3697623930bec62efb06014a54cd961a7199497",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/139.0.7258.154/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "4eab0a528bfc0a00b9935eb8a37c5154705146392060e7a44c744f16c293ba7f",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/139.0.7258.154/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "b0bafb0c23996ced6994e7eb327c881ea0d4f4803424246ce7cef70dfef0cc56",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/139.0.7258.154/win64/chrome-headless-shell-win64.zip",
            "integrity": "143ac74e6dba022ecfebeff70ad399060ffec0348d93adc5c31d9e4020ab702c",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "140.0.7339.207": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "39fcb6acdf442e5560bc3cdd6ec0a7b3174998a9761f391c156a4d26df5a0b19",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "df4545512e527b29149f9166015a1ca3e2a743816325264fec9f18fd54f355e2",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "0418c337d53a12dc0908527fcd0478a135497a147a33ae6a39113a16c64fe9f3",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.207/win64/chrome-headless-shell-win64.zip",
            "integrity": "6fb1836cad8148016fa28df1a77baa1d77aaadf04e483fbeb12c73e8184bad90",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "141.0.7390.54": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.54/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "cba167189d1e676a10bb0a1d52b43a26eb7d6c15dd6f05ae76cff100c30d547a",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.54/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "7f7ab9a831391fa7d183b08fcf90ba6bcd5023e0663efd335faec40ece3eb749",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.54/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "6a0b3f4f13adf89f5fd8618ba68ef9ef0ab375e4f53fad4d5d56cf801054b7f2",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.54/win64/chrome-headless-shell-win64.zip",
            "integrity": "1264ee192ca001359b4527d195d635c4f33312543a90e31359bac38931d34f81",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "141.0.7390.65": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.65/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "74d44ced303a896494cfae337bce4996bf81f2941e302784068d4699b4501415",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.65/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "f0ca463bc331c86e15db1cdc32f847d632a1a8d34e6e8d8a24cb2564131a7c08",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.65/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "8d30ea656885698e0126c25b0ea27d946a9ae7a0349bf1ef2cd9ebb5ac1a4ac1",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.65/win64/chrome-headless-shell-win64.zip",
            "integrity": "2634b1a2d2893de6472d8be5ca74fee31c2a10c1d2a68d8f7a06fb08a970c3cf",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "141.0.7390.78": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.78/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "2c117293276ef874ac1ecb6d0128beb4eb92e5b7d6b37b93aec63baf322d9640",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.78/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "3ff433a73c84f3571ad9aa55a97f5164aa809ca8f108534f19b7e4f3ab630e6b",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.78/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "6445e0c4a88bf7cbe741803cf3ec74b4472c804bffab4914d2c79bfe74d7d98a",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.78/win64/chrome-headless-shell-win64.zip",
            "integrity": "3185d2c351ef0c91cb763c3568582c29b3eb4e0f7bcd5e54b27c013a66f787f9",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "141.0.7390.122": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.122/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "5ab96651d2f2d2d6501de60fec918c562c4c02fde497da0688bd82c4994a04eb",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.122/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "819199757ca223fafb401f1d20215d369a130bbd88c4ba96334bb65ac2b7d4f2",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.122/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "6bd2b26e1d89f5c3939969e337ef62133631b044f28e517e5ab2a195ce7d7e7e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/141.0.7390.122/win64/chrome-headless-shell-win64.zip",
            "integrity": "04765b5879b09c22152b9c753778851a003ee2009269e4d049245daa774b46ce",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "142.0.7444.6": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.6/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "155fe3738dc90b9723752974eb93a0500de631fe5de0732be1a79d00ff565962",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.6/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "16882cc7cb5b86d491ecd9669c9d9a3b2c591f9ac031774476cf4f99c254b579",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.6/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "ad608b5afff4dec60778ed83fab4f0d6b8563ab7ac94b3b48b1e0cebabec392e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.6/win64/chrome-headless-shell-win64.zip",
            "integrity": "f3d396ad4b6244feee263a6b39d8e8b32f1d568db74a333c2e7679e0fcd7ab09",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "142.0.7444.34": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.34/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "175179055a978925dc29a320c94593e6e32341eb3701d1cc68b49ef455487e5c",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.34/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "2fbecbbb7ff4e727f5cd2e57bd2bb21c8d974cb02628b805c9723330c5b57c42",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.34/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "cf9e3338823630a9d4e94e2e5e015f209e5f894cb4a5156c8c654dfb13e990aa",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.34/win64/chrome-headless-shell-win64.zip",
            "integrity": "982d1fc0f1772c55a094df7040d11ded8187be6a07bf086c49e5cf1857404485",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "142.0.7444.175": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.175/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "a2d6c8acd6b35b7e309c4f471a8198111cba34bf8ff22c8d8a11f555b36c689e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.175/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "9e55c79de8a8ed2e00c2e15421763f5342ec1c100f31426da0643071fd10aadc",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.175/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "9ec03f0a088d76e878f916aa01937a8684924bb8c2e82b3daf939dc22eaeb5c3",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/142.0.7444.175/win64/chrome-headless-shell-win64.zip",
            "integrity": "09205bd27a13774b2c30fe1198513660c9cdef5959931f0e7a410fadbb6fd698",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "143.0.7459.0": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7459.0/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "79a3a4d3a5f9efae04dbb7c2164393ff8fee5f352ec73e36900848c75f4f906f",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7459.0/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "cdba96e69a423adc1f2647f35643a10e33260b4dfcc233977f3724f28bffd8f2",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7459.0/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "56eb0c57958b50dc6c0de810ea9fcf1ff800baf2a4b14ae0fea536e633806098",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7459.0/win64/chrome-headless-shell-win64.zip",
            "integrity": "506b23250323f3eb4cdfe298cfd599571e428f6f3a64e86818ee975f4e585b75",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "143.0.7482.0": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7482.0/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "4bc6d611d55dc96b213c8605cb8ac27d3c21973bf8b663df4cbf756c989e6745",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7482.0/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "830cc2aafedbe7c9fe671c9898046f8900c06da89d12653ddc3ef26084d2f516",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7482.0/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "5b5792f5c2d05c3f1f782346910869b61a37b9003f212315b19f4e46710cf8b9",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7482.0/win64/chrome-headless-shell-win64.zip",
            "integrity": "19bdbf6e1579b6c056b74709520ac9df573f4e80e4f026cc2360a29443cf6c0c",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "143.0.7499.25": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.25/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "c57508303e15a73770ff0d014a765f63d9112d5e012c269597a7a87f518bf8b4",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.25/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "65349e0e7293f643873ccad66b85517c704bc26b402e8e8d99d347cbad0870f9",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.25/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "841a229494b0c2603fb5741e4b2b999732202153eb833ecec3e7afc2b5fd93db",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.25/win64/chrome-headless-shell-win64.zip",
            "integrity": "8f7e7ef75fd3b39294d99d76989e9e6c128efd8b535c6ad07014971e7e96a6ca",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "143.0.7499.169": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.169/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "f0325a860a17830ce889cb9b636f5af44586885f91b07733ea8609806264d218",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.169/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "82af77ca23fda2a1832414a8f08d0ced3c6a002bd4598a7080a7cbc43065b903",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.169/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "c3b2899dde82291b764a33ffa7ac8da928ebd9fbc36120fe28f4d047380530d2",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.169/win64/chrome-headless-shell-win64.zip",
            "integrity": "0dcc6a1f0fb031c2b6d925aa0a80ed9793956b817aa4c783c4edbf2435288716",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "143.0.7499.192": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.192/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "2e4f1d32c73ed133a5ecabf5bbf03eeb1f3830df15610df6d8058fe6fb741114",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.192/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "32abd3b2f8236310edc46f782613919b2ab3a833ca81a11c5d2229cfdfc3c499",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.192/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "86765a047c35c4b25d29a6da1816c43004774801ba23156a1b21e9fa7e33c7c6",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/143.0.7499.192/win64/chrome-headless-shell-win64.zip",
            "integrity": "5c6a6b71acc58f51d17c243e8e09e392753f95ea01bc7ec9a715eb3e1fd9e6fb",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "144.0.7531.0": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7531.0/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "1419fa328bd7ea2697f26412ec693867516e4ef23c32eb13143a0b0b179b604b",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7531.0/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "792cbf9b77219b4476e41c49647bcd15e55f0988002fa1e4e6a720eb430c7eda",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7531.0/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "f0c1917769775e826dfa69936381d0d95b06fe67cf631ecd842380d5de0e4c7f",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7531.0/win64/chrome-headless-shell-win64.zip",
            "integrity": "6ce0f20dd743a804890f45f5349370e1aa7cd3ac3482c04686fcff5fafd01bb3",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "144.0.7559.31": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.31/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "3ae0f29abb399bb2435f28ed36c57e237005836eb9e925ef8818cbff57e4174d",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.31/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "a06f546eedb68edb68b81f103f03fc66a5242ef7ff70f7edc54949623d2e5985",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.31/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "bfa5b942f01d4ed40fbbb3f8b6cd295493f8e1baa2442e51b1c826a14142787c",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.31/win64/chrome-headless-shell-win64.zip",
            "integrity": "72f189cc84dbf73858f1738fd3f7a9c944e7614561b6983b7cae3ec0379ade70",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "144.0.7559.133": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.133/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "b0c120c9c3989823656f75514721d6715590524747e26feeacc18d34ef78225e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.133/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "4f801ad4cc1d6e73f46cd3c4583551b272c0685be862d801c586a414b9c2ae4c",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.133/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "6c0c5b73553394827fb6c9e5cc6be1cbcab6a409cf18296ca114dc9e9bb43c2e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/144.0.7559.133/win64/chrome-headless-shell-win64.zip",
            "integrity": "f023c7843d011727cee50d12b32902e7fc1c1672b1fbd41adb17bfdd95eb32b9",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "145.0.7586.0": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7586.0/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "0a2ff0fc9eb5958b7b420f20e3968f424be7423fef89739e71565a48aa073a57",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7586.0/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "e6076b1201d86f74c5eab982a239d5af83e66b1aa4d780bcb792698790e01d87",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7586.0/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "b74dbcf5543d916b02d0a133e2e7c6a4de251f06733f72c2c15ea8c42213f63b",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7586.0/win64/chrome-headless-shell-win64.zip",
            "integrity": "df1e612dc3b1615e182a1f11821052995913c39df37caa52699de21a68d030d2",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "145.0.7632.76": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7632.76/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "262d778300a8d2657ead75ba38a15c91f4dc6d7eb54713ba750264bd65dd2a51",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7632.76/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "a81b60f42696dd471617d67f92bf16fe47d4639f75c4d700606e90991d7a5e0d",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7632.76/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "bfb90a62a36a47a54e96ea3e36f12fd499276bb8bfae97aafbe19079f41f1b1b",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/145.0.7632.76/win64/chrome-headless-shell-win64.zip",
            "integrity": "85b44dbb12eb7f3d7d0733f71fd8da16d1abc7fb95812684d31896264d42c853",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "146.0.7680.4": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/146.0.7680.4/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "794f8e3ecc57972c125076162edd201b110602263d50e79c4ad3cf7e5910fd7c",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/146.0.7680.4/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "fb1e69e2b05b368a558745b2901ee7f65715f26428a891382d79561d87e72c4c",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/146.0.7680.4/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "3cfe2ec50faf34bf3974a0bcd1e93e2bac69160169b8c33e6c86665bd1d1de6c",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/146.0.7680.4/win64/chrome-headless-shell-win64.zip",
            "integrity": "a89e7bb4e92d23b4083f435f22734e2a339732d861a7474eb736bc908fdfbc25",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
    "147.0.7687.0": {
        "linux": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/147.0.7687.0/linux64/chrome-headless-shell-linux64.zip",
            "integrity": "1ac33f89306327af43be159c03ca4a26486de0858f42fe52394acdef50364143",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-linux64/chrome-headless-shell",
            },
        },
        "mac": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/147.0.7687.0/mac-x64/chrome-headless-shell-mac-x64.zip",
            "integrity": "169ff49c465cfda52931395e61861e146dfc5013e92c01ca792db5acea858d0b",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-x64/chrome-headless-shell",
            },
        },
        "mac_arm": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/147.0.7687.0/mac-arm64/chrome-headless-shell-mac-arm64.zip",
            "integrity": "aeaaaaa4d68193a21bed04c44ddeb1230232707b4ea1d845a92925787509cd8e",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-mac-arm64/chrome-headless-shell",
            },
        },
        "win64": {
            "url": "https://storage.googleapis.com/chrome-for-testing-public/147.0.7687.0/win64/chrome-headless-shell-win64.zip",
            "integrity": "4d6d79bcbcb22084df6e3a3d3a2caff67d6c0fa488d63f0c7ec1526f9553db8c",
            "exclude_patterns": [
                "**/*.log",
            ],
            "named_files": {
                "CHROME-HEADLESS-SHELL": "chrome-headless-shell-win64/chrome-headless-shell.exe",
            },
        },
    },
}
